version: '3'
services:
  familytree:
    build: ./web
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file: .env
    restart: always
    volumes:
      - data:/usr/src/app/project/static
    links:
      - postgres:dbserver
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - data:/www/static
    depends_on:
      - familytree
  postgres:
    image: postgres
    env_file: .env-pg
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
